import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import styles from '../styles/Home.module.css'
import {Container} from '../styles/Home.style'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CineFlex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Container >
      <Banner />
    </Container>
      
    </div>
  )
}


